/* ============================================================
   CINEMATIC SITE — scroll-driven fly-through engine (vanilla, zero deps)
   ------------------------------------------------------------
   Apple-style scrub: preloads N JPEG frames (ONE continuous AI
   fly-through), then maps scroll progress through the tall .scrub
   section to a frame index. Caption "beats" fade in/out over the
   footage at progress windows. Editorial blocks reveal on enter.

   YOU DO NOT EDIT THIS FILE to change the journey.
   To wire YOUR fly-through:
     1. Drop your exported frames in  assets/frames/  named
        frame-001.jpg, frame-002.jpg, ... (3-digit, 1-based).
     2. Set the frame count in index.html on the .scrub section:
        <section class="scrub" data-frames="120">  ← your count
     3. Bump CACHE_BUST below by 1 whenever you replace the frames
        (forces the browser to re-fetch instead of serving stale).
   Everything else is automatic.
   ============================================================ */

(function () {
  "use strict";

  /* Bump this integer by 1 each time you swap the frames in
     assets/frames/ so the browser cache can't serve stale images. */
  var CACHE_BUST = 6;

  /* ---- IntersectionObserver: reveal-on-enter for editorial blocks ---- */
  var io = new IntersectionObserver(
    function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add("is-visible");
          io.unobserve(entry.target);
        }
      });
    },
    { threshold: 0.18, rootMargin: "0px 0px -8% 0px" }
  );
  document.querySelectorAll("[data-reveal]").forEach(function (el) {
    io.observe(el);
  });

  var prefersReducedEarly = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  /* ============================================================
     MOTION LAYER (additive)
     Self-contained. Never touches the scrub engine below.
     All effects are no-ops under prefers-reduced-motion.
     ============================================================ */

  /* ---- 1. Masked line-by-line reveal for section titles ----
     Splits a heading's <br>-separated lines into:
       .ml-line > .ml-line__inner
     so the parent clip + inner translate produce a "type rises behind a
     mask" effect, staggered per line. The paired eyebrow gets a clip-up.
     Targets existing section titles WITHOUT changing their text. */
  function buildMaskedTitle(h) {
    if (h.dataset.mlBuilt) return;
    h.dataset.mlBuilt = "1";
    var html = h.innerHTML;
    var parts = html.split(/<br\s*\/?>/i);
    var frag = "";
    for (var i = 0; i < parts.length; i++) {
      var seg = parts[i].trim();
      if (!seg) continue;
      frag += '<span class="ml-line"><span class="ml-line__inner" style="--ml-delay:' +
        (i * 0.085).toFixed(3) + 's">' + seg + "</span></span>";
    }
    h.innerHTML = frag;
    h.classList.add("ml-reveal");
  }

  if (!prefersReducedEarly) {
    var titleSelectors = [
      ".editorial__title",
      ".amenities__title",
      ".bleed__title",
      ".manifesto__title",
      ".contact__title",
    ];
    var mlTitles = document.querySelectorAll(titleSelectors.join(","));
    mlTitles.forEach(function (h) { buildMaskedTitle(h); });

    var mlEyebrows = document.querySelectorAll(
      ".editorial__text .eyebrow, .amenities__head .eyebrow, " +
      ".bleed__content .eyebrow, .manifesto__inner .eyebrow, .contact__text .eyebrow"
    );
    mlEyebrows.forEach(function (e) { e.classList.add("ml-eyebrow"); });

    var mlIO = new IntersectionObserver(
      function (entries) {
        entries.forEach(function (entry) {
          if (entry.isIntersecting) {
            entry.target.classList.add("is-shown");
            mlIO.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.2, rootMargin: "0px 0px -10% 0px" }
    );
    mlTitles.forEach(function (h) { mlIO.observe(h); });
    mlEyebrows.forEach(function (e) { mlIO.observe(e); });
  }

  /* ---- 2. Animated counters (stats) ---- */
  if (!prefersReducedEarly) {
    var statsSection = document.querySelector(".stats");
    if (statsSection) {
      var counted = false;
      function runCounters() {
        if (counted) return;
        counted = true;
        var nums = statsSection.querySelectorAll(".stat__num");
        nums.forEach(function (numEl) {
          var unitEl = numEl.querySelector(".stat__unit");
          var unitHTML = unitEl ? unitEl.outerHTML : "";
          var unitText = unitEl ? (unitEl.textContent || "") : "";
          var raw = (numEl.textContent || "").replace(unitText, "").trim();
          // Handle space as thousands separator: "1 512" → 1512
          var m = raw.replace(/[\s  ]/g, "").match(/^(\d+)/);
          if (!m) return; // non-numeric stats stay static
          var target = parseInt(m[1], 10);
          // Format back with narrow no-break space for thousands
          function fmtNum(n) {
            var s = String(n);
            return s.length > 3 ? s.slice(0, s.length - 3) + " " + s.slice(-3) : s;
          }
          var DURATION = 1400;
          var start = null;
          numEl.classList.add("is-counting");
          function tick(ts) {
            if (start === null) start = ts;
            var t = Math.min((ts - start) / DURATION, 1);
            var eased = 1 - Math.pow(1 - t, 3); // easeOutCubic
            var val = Math.round(eased * target);
            numEl.innerHTML = fmtNum(val) + unitHTML;
            if (t < 1) {
              window.requestAnimationFrame(tick);
            } else {
              numEl.innerHTML = fmtNum(target) + unitHTML;
              numEl.classList.remove("is-counting");
            }
          }
          window.requestAnimationFrame(tick);
        });
      }
      var statsIO = new IntersectionObserver(
        function (entries) {
          entries.forEach(function (entry) {
            if (entry.isIntersecting) { runCounters(); statsIO.disconnect(); }
          });
        },
        { threshold: 0.4 }
      );
      statsIO.observe(statsSection);
    }
  }

  /* ---- 3. Soft parallax on full-bleed images ---- */
  (function initParallax() {
    if (prefersReducedEarly) return;
    if (window.matchMedia("(max-width: 820px)").matches) return;
    var imgs = [].slice.call(document.querySelectorAll(".bleed__img"));
    if (!imgs.length) return;
    var MAX_SHIFT = 0.12; // <=12% of element height
    var pTicking = false;
    function updateParallax() {
      var vh = window.innerHeight;
      for (var i = 0; i < imgs.length; i++) {
        var img = imgs[i];
        var section = img.parentElement;
        var rect = section.getBoundingClientRect();
        if (rect.bottom < 0 || rect.top > vh) continue; // offscreen, skip
        var center = rect.top + rect.height / 2;
        var rel = (center - vh / 2) / (vh / 2 + rect.height / 2);
        if (rel > 1) rel = 1; if (rel < -1) rel = -1;
        var shift = -rel * MAX_SHIFT * rect.height;
        img.style.setProperty("--py", shift.toFixed(1) + "px");
      }
      pTicking = false;
    }
    window.addEventListener("scroll", function () {
      if (!pTicking) { window.requestAnimationFrame(updateParallax); pTicking = true; }
    }, { passive: true });
    window.addEventListener("resize", function () {
      if (!pTicking) { window.requestAnimationFrame(updateParallax); pTicking = true; }
    }, { passive: true });
    updateParallax();
  })();

  /* ---- 4. Intro load reveal (nav) ----
     Mark body.intro-ready (nav hidden via CSS), then flip .is-loaded next
     frame to play the fade-in. setTimeout fallback ensures it fires even
     in background tabs where rAF is throttled. */
  if (!prefersReducedEarly) {
    document.body.classList.add("intro-ready");
    var introFired = false;
    function fireIntro() {
      if (introFired) return;
      introFired = true;
      document.body.classList.add("is-loaded");
    }
    window.requestAnimationFrame(function () {
      window.requestAnimationFrame(fireIntro);
    });
    setTimeout(fireIntro, 300);
  }

  /* ---- Scroll-progress bar + nav state (rAF-throttled) ---- */
  var progress = document.querySelector(".scroll-progress");
  var nav = document.getElementById("nav");
  var ticking = false;
  function onScroll() {
    var scrollTop = window.scrollY || document.documentElement.scrollTop;
    var docH = document.documentElement.scrollHeight - window.innerHeight;
    var pct = docH > 0 ? (scrollTop / docH) * 100 : 0;
    if (progress) progress.style.width = pct + "%";
    if (nav) {
      if (scrollTop > 40) nav.classList.add("is-scrolled");
      else nav.classList.remove("is-scrolled");
    }
    ticking = false;
  }
  window.addEventListener("scroll", function () {
    if (!ticking) { window.requestAnimationFrame(onScroll); ticking = true; }
  }, { passive: true });
  onScroll();

  var prefersReduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  function smoothstep(a, b, x) {
    if (x <= a) return 0;
    if (x >= b) return 1;
    var t = (x - a) / (b - a);
    return t * t * (3 - 2 * t);
  }

  /* ============================================================
     SCROLL-DRIVEN FLY-THROUGH (Apple-style scrub)
     ============================================================ */
  (function initScrub() {
    var section = document.querySelector(".scrub");
    if (!section) return;

    var stage = section.querySelector(".scrub__stage");
    var canvas = section.querySelector(".scrub__canvas");
    var ctx = canvas.getContext("2d");
    var loader = document.getElementById("loader");
    var loaderBar = document.getElementById("loaderBar");
    var loaderPct = document.getElementById("loaderPct");
    var cue = document.getElementById("scrubCue");
    /* Inclut le logo hero (.scrub__hero-logo) qui porte aussi data-in/data-out */
    var beats = Array.prototype.slice.call(section.querySelectorAll("[data-in][data-out]"));

    /* Frame count comes from data-frames on the .scrub section in index.html.
       Fallback 1 = a single static frame-001.jpg (so the page still renders
       a hero even before you've set your real count). */
    var FRAME_COUNT = parseInt(section.dataset.frames, 10) || 1;
    var LAST = FRAME_COUNT - 1;
    var FRAME_BASE = "assets/frames/frame-";
    var FADE = 0.05; // fade margin (progress units) for caption in/out

    var frames = new Array(FRAME_COUNT);
    var loadedCount = 0;
    var ready = false;

    var isSmall = window.matchMedia("(max-width: 820px)").matches;
    if (isSmall) section.classList.add("scrub--static");

    function pad3(n) {
      n = String(n + 1);
      return n.length >= 3 ? n : ("000" + n).slice(-3);
    }

    /* ---- Canvas sizing (DPR-aware) ---- */
    var cssW = 0, cssH = 0, dpr = 1, lastDrawn = -1;
    function resizeCanvas() {
      var rect = stage.getBoundingClientRect();
      var w = Math.round(rect.width) || stage.clientWidth || window.innerWidth;
      var h = Math.round(rect.height) || stage.clientHeight || window.innerHeight;
      var d = Math.min(Math.max(window.devicePixelRatio || 1, 1), 2);
      if (w === cssW && h === cssH && d === dpr) return false;
      cssW = w; cssH = h; dpr = d;
      canvas.width = Math.round(cssW * dpr);
      canvas.height = Math.round(cssH * dpr);
      canvas.style.width = cssW + "px";
      canvas.style.height = cssH + "px";
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      lastDrawn = -1;
      return true;
    }

    /* ---- Cover-fit draw (preserve aspect, center-crop) ---- */
    function coverParams(img) {
      var iw = img.naturalWidth, ih = img.naturalHeight;
      var scale = Math.max(cssW / iw, cssH / ih);
      var dw = iw * scale, dh = ih * scale;
      return [(cssW - dw) / 2, (cssH - dh) / 2, dw, dh];
    }
    function drawFrame(i) {
      if (i < 0) i = 0;
      if (i > LAST) i = LAST;
      var img = frames[i];
      if (!img || !img.complete || !img.naturalWidth) return;
      lastDrawn = i;
      var p = coverParams(img);
      ctx.clearRect(0, 0, cssW, cssH);
      ctx.globalAlpha = 1;
      ctx.drawImage(img, p[0], p[1], p[2], p[3]);
    }

    /* Play the journey from the first frame. */
    var START_IDX = 0;

    /* ---- Progress 0->1 across the section's scroll range ---- */
    function getProgress() {
      var rect = section.getBoundingClientRect();
      var travel = section.offsetHeight - window.innerHeight;
      if (travel <= 0) return 0;
      var p = -rect.top / travel;
      return p < 0 ? 0 : p > 1 ? 1 : p;
    }

    /* ---- Caption beats + logo hero: fade in/out sur [in, out] ----
       Les .scrub__beat reçoivent aussi un translateY pour l'effet de montée.
       Le logo (.scrub__hero-logo) reçoit uniquement l'opacité. */
    function renderBeats(p) {
      for (var i = 0; i < beats.length; i++) {
        var el = beats[i];
        var inP = parseFloat(el.dataset.in);
        var outP = parseFloat(el.dataset.out);
        var op = smoothstep(inP, inP + FADE, p) * (1 - smoothstep(outP - FADE, outP, p));
        el.style.opacity = String(op);
        if (el.classList.contains("scrub__beat")) {
          el.style.transform = "translateY(" + (1 - op) * 18 + "px)";
        }
        el.style.pointerEvents = op > 0.5 ? "auto" : "none";
      }
    }

    /* ---- Scroll -> frame mapping ----
       The hero is ONE continuous fly-through, so scroll maps directly and
       linearly to the frame index. */
    function frameForProgress(p) {
      if (p <= 0) return 0;
      if (p >= 1) return LAST;
      return Math.round(p * LAST);
    }

    function render(p) {
      resizeCanvas();
      var idx = frameForProgress(p);
      if (idx !== lastDrawn) drawFrame(idx);
      renderBeats(p);
      if (cue) cue.style.opacity = String(1 - smoothstep(0.02, 0.10, p));
    }

    /* ---- Lissage scroll -> frame (technique "lerp ticker") ----
       Le scroll écrit UNIQUEMENT targetProgress. Un rAF loop séparé
       interpole currentProgress vers cette cible (facteur LERP) et c'est
       currentProgress qui pilote le rendu. Ça évite le saut brut d'une
       frame à l'autre sur un scroll rapide (roulette, fin de scrub, etc.)
       — même principe que le lerp video.currentTime des sites vidéo. */
    var targetProgress = 0;
    var currentProgress = 0;
    var LERP = 0.14;
    var tickerRunning = false;

    function onScrubScroll() {
      targetProgress = getProgress();
    }

    function tick() {
      if (!tickerRunning) return;
      currentProgress += (targetProgress - currentProgress) * LERP;
      if (Math.abs(targetProgress - currentProgress) < 0.0004) {
        currentProgress = targetProgress;
      }
      render(currentProgress);
      requestAnimationFrame(tick);
    }

    function enableScrub() {
      ready = true;
      resizeCanvas();
      if (prefersReduced || isSmall) {
        drawFrame(START_IDX);
        if (cue) cue.style.opacity = "0";

        if (prefersReduced) {
          /* Mouvement réduit : image fixe, tout visible */
          beats.forEach(function(b) { b.style.opacity = "1"; b.style.transform = "none"; });
          window.addEventListener("resize", function() { resizeCanvas(); drawFrame(0); });
          return;
        }

        /* MOBILE AUTO-PLAY : fly-through cinématique joué automatiquement en 6s */
        var startTime = null;
        var DURATION = 6000;
        function autoPlay(ts) {
          if (!startTime) startTime = ts;
          var p = Math.min((ts - startTime) / DURATION, 1);
          drawFrame(Math.round(p * LAST));
          renderBeats(p);
          if (p < 1) requestAnimationFrame(autoPlay);
        }
        requestAnimationFrame(autoPlay);
        window.addEventListener("resize", function() { resizeCanvas(); });
        return;
      }
      targetProgress = currentProgress = getProgress();
      render(currentProgress);
      window.addEventListener("scroll", onScrubScroll, { passive: true });
      window.addEventListener("resize", function () { if (ready) targetProgress = getProgress(); });
      tickerRunning = true;
      requestAnimationFrame(tick);
    }

    /* ---- Preload all frames; paint frame 0 the instant it lands ---- */
    function bumpLoader() {
      var pct = Math.round((loadedCount / FRAME_COUNT) * 100);
      if (loaderBar) loaderBar.style.width = pct + "%";
      if (loaderPct) loaderPct.textContent = pct + "%";
    }
    var firstPainted = false;
    function preload() {
      resizeCanvas();
      for (var i = 0; i < FRAME_COUNT; i++) {
        (function (i) {
          var img = new Image();
          img.decoding = "async";
          img.onload = img.onerror = function () {
            loadedCount++;
            bumpLoader();
            if (i === 0 && !firstPainted && img.naturalWidth) {
              firstPainted = true;
              drawFrame(0);
            }
            if (loadedCount === FRAME_COUNT) {
              if (loader) loader.classList.add("is-done");
              enableScrub();
            }
          };
          img.src = FRAME_BASE + pad3(i) + ".jpg?v=" + CACHE_BUST;
          frames[i] = img;
        })(i);
      }
    }
    preload();
  })();
})();
